name: example
version: 0.0.1
description:
  The purpose is testing that our dependency version constraints don't conflict
  with popular packages.

publish_to: none

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  database:
  database_adapter_algolia:
  database_adapter_elasticsearch:
  database_adapter_postgre:
  search:

  angular: any

dependency_overrides:
  database:
    path: '../../database'
  database_adapter_algolia:
    path: '../../adapters/algolia'
  database_adapter_elasticsearch:
    path: '../../adapters/elasticsearch'
  database_adapter_postgre:
    path: '../../adapters/postgre'
  search:
    path: '../../search'