name: example
version: 0.0.1
description:
  The purpose is testing that our dependency version constraints don't conflict with popular
  packages.

publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  database:
  database_adapter_algolia:
  database_adapter_elasticsearch:
  database_adapter_firestore_flutter:
  database_adapter_postgre:
  database_adapter_sqlite:
  search:

  flutter:
    sdk: flutter

dependency_overrides:
  database:
    path: '../../database'
  database_adapter_algolia:
    path: '../../adapters/algolia'
  database_adapter_elasticsearch:
    path: '../../adapters/elasticsearch'
  database_adapter_firestore_flutter:
    path: '../../adapters/firestore_flutter'
  database_adapter_postgre:
    path: '../../adapters/postgre'
  database_adapter_sqlite:
    path: '../../adapters/sqlite'
  search:
    path: '../../search'